import type { ColumnId, DetailedRowData } from "@/types";

export function getDetailedData(columnId: ColumnId): DetailedRowData[] {
  const baseData: DetailedRowData[] = [
    {
      id: "№82 от 18.09.2024",
      carType: "полувагон",
      client: "Т-СЕРВИС Л.",
      manager: "Иванов И.И.",
      shipper: "АО Щуба",
      cargo: "Уголь каменный мл",
      weight: 69,
      requestedCars: 10,
      mandatory: true,
      status: "обеспечен 3 из 10",
      departureStation: "Шубарколь",
      destinationStation: "Лужская",
      returnStation: "Шубарколь",
      calculatedTurnover: 32,
      approach: 0,
      loading: 5,
      loadedRun: 11,
      unloading: 3,
      return: 13,
      carDays: 32,
      clientRate: "757 456,00",
      emptyTariff: "250 230,00",
      loadedTariff: "416 482,00",
      provisionIncome: "90 744,00",
      dailyProfitability: "2 835,75",
      totalAmount: "757 456,00",
      deadEndPerDay: "1 200,00",
      supply: "да",
      day1: 5,
      day2: 3,
      day3: 11,
      wagonNumber: "",
      note: "",
    },
    {
      id: "Заявка №123",
      carType: "полувагон",
      client: "ООО ТрансЛогистик",
      manager: "Петров П.П.",
      shipper: "ПАО Уголь",
      cargo: "Уголь энергетический",
      weight: 72,
      requestedCars: 5,
      mandatory: true,
      status: "обеспечен",
      departureStation: "Магдаля",
      destinationStation: "Шубарколь",
      returnStation: "Магдаля",
      calculatedTurnover: 28,
      approach: 2,
      loading: 4,
      loadedRun: 10,
      unloading: 3,
      return: 9,
      carDays: 28,
      clientRate: "757 456,00",
      emptyTariff: "250 230,00",
      loadedTariff: "416 482,00",
      provisionIncome: "90 744,00",
      dailyProfitability: "2 835,75",
      totalAmount: "757 456,00",
      deadEndPerDay: "1 200,00",
      supply: "да",
      day1: 4,
      day2: 2,
      day3: 10,
      wagonNumber: "111111",
      note: "",
    },
    {
      id: "Заявка №124",
      carType: "цистерна",
      client: "ООО НефтеТранс",
      manager: "Сидоров С.С.",
      shipper: "АО НефтеПром",
      cargo: "Нефть сырая",
      weight: 65,
      requestedCars: 8,
      mandatory: true,
      status: "обеспечен с корректировкой",
      departureStation: "Лужская",
      destinationStation: "Магдаля",
      returnStation: "Лужская",
      calculatedTurnover: 30,
      approach: 1,
      loading: 3,
      loadedRun: 12,
      unloading: 4,
      return: 10,
      carDays: 30,
      clientRate: "757 456,00",
      emptyTariff: "250 230,00",
      loadedTariff: "416 482,00",
      provisionIncome: "90 744,00",
      dailyProfitability: "2 835,75",
      totalAmount: "757 456,00",
      deadEndPerDay: "1 200,00",
      supply: "да",
      day1: 3,
      day2: 4,
      day3: 12,
      wagonNumber: "222222",
      note: "",
    },
    {
      id: "Заявка №125",
      carType: "крытый",
      client: "ООО ГрузоПеревозки",
      manager: "Козлов К.К.",
      shipper: "ООО ПродуктЛогистик",
      cargo: "Продукты питания",
      weight: 55,
      requestedCars: 3,
      mandatory: false,
      status: "обеспечен, с корректировкой по ограничениям",
      departureStation: "Шубарколь",
      destinationStation: "Магдаля",
      returnStation: "Шубарколь",
      calculatedTurnover: 25,
      approach: 0,
      loading: 2,
      loadedRun: 9,
      unloading: 2,
      return: 12,
      carDays: 25,
      clientRate: "757 456,00",
      emptyTariff: "250 230,00",
      loadedTariff: "416 482,00",
      provisionIncome: "90 744,00",
      dailyProfitability: "2 835,75",
      totalAmount: "757 456,00",
      deadEndPerDay: "1 200,00",
      supply: "да",
      day1: 2,
      day2: 2,
      day3: 9,
      wagonNumber: "333333",
      note: "",
    },
    {
      id: "Заявка №126",
      carType: "платформа",
      client: "ЗАО СтройМатериалы",
      manager: "Николаев Н.Н.",
      shipper: "ООО СтройБаза",
      cargo: "Пиломатериалы",
      weight: 48,
      requestedCars: 6,
      mandatory: true,
      status: "не обеспечен, по ограничениям",
      departureStation: "Магдаля",
      destinationStation: "Лужская",
      returnStation: "Магдаля",
      calculatedTurnover: 27,
      approach: 1,
      loading: 3,
      loadedRun: 10,
      unloading: 3,
      return: 10,
      carDays: 27,
      clientRate: "757 456,00",
      emptyTariff: "250 230,00",
      loadedTariff: "416 482,00",
      provisionIncome: "90 744,00",
      dailyProfitability: "2 835,75",
      totalAmount: "757 456,00",
      deadEndPerDay: "1 200,00",
      supply: "нет",
      day1: 3,
      day2: 3,
      day3: 10,
      wagonNumber: "",
      note: "1234, 33",
    },
    {
      id: "Заявка №127",
      carType: "полувагон",
      client: "ООО МеталлТорг",
      manager: "Смирнов С.С.",
      shipper: "ПАО МеталлПром",
      cargo: "Металлопрокат",
      weight: 70,
      requestedCars: 4,
      mandatory: true,
      status: "не обеспечен, по ограничениям",
      departureStation: "Шубарколь",
      destinationStation: "Лужская",
      returnStation: "Шубарколь",
      calculatedTurnover: 29,
      approach: 1,
      loading: 4,
      loadedRun: 11,
      unloading: 3,
      return: 10,
      carDays: 29,
      clientRate: "757 456,00",
      emptyTariff: "250 230,00",
      loadedTariff: "416 482,00",
      provisionIncome: "90 744,00",
      dailyProfitability: "2 835,75",
      totalAmount: "757 456,00",
      deadEndPerDay: "1 200,00",
      supply: "нет",
      day1: 4,
      day2: 3,
      day3: 11,
      wagonNumber: "",
      note: "1234, 33",
    },
    {
      id: "Заявка №128",
      carType: "хоппер",
      client: "ООО АгроТранс",
      manager: "Кузнецов К.К.",
      shipper: "АО АгроХолдинг",
      cargo: "Зерно",
      weight: 60,
      requestedCars: 7,
      mandatory: false,
      status: "не обеспечен, по ограничениям",
      departureStation: "Магдаля",
      destinationStation: "Шубарколь",
      returnStation: "Магдаля",
      calculatedTurnover: 26,
      approach: 0,
      loading: 3,
      loadedRun: 10,
      unloading: 3,
      return: 10,
      carDays: 26,
      clientRate: "757 456,00",
      emptyTariff: "250 230,00",
      loadedTariff: "416 482,00",
      provisionIncome: "90 744,00",
      dailyProfitability: "2 835,75",
      totalAmount: "757 456,00",
      deadEndPerDay: "1 200,00",
      supply: "нет",
      day1: 3,
      day2: 3,
      day3: 10,
      wagonNumber: "",
      note: "1234, 33",
    },
    {
      id: "Заявка №129",
      carType: "полувагон",
      client: "ООО ТрансУголь",
      manager: "Морозов М.М.",
      shipper: "ПАО УгольПром",
      cargo: "Уголь коксующийся",
      weight: 68,
      requestedCars: 5,
      mandatory: true,
      status: "не обеспечен, по ограничениям",
      departureStation: "Лужская",
      destinationStation: "Магдаля",
      returnStation: "Лужская",
      calculatedTurnover: 28,
      approach: 1,
      loading: 3,
      loadedRun: 10,
      unloading: 4,
      return: 10,
      carDays: 28,
      clientRate: "757 456,00",
      emptyTariff: "250 230,00",
      loadedTariff: "416 482,00",
      provisionIncome: "90 744,00",
      dailyProfitability: "2 835,75",
      totalAmount: "757 456,00",
      deadEndPerDay: "1 200,00",
      supply: "нет",
      day1: 3,
      day2: 4,
      day3: 10,
      wagonNumber: "",
      note: "1234, 33",
    },
    {
      id: "Заявка №130",
      carType: "полувагон",
      client: "ЗАО ГорноМеталл",
      manager: "Волков В.В.",
      shipper: "ООО ГорноДобыча",
      cargo: "Руда железная",
      weight: 72,
      requestedCars: 8,
      mandatory: true,
      status: "обеспечен",
      departureStation: "Шубарколь",
      destinationStation: "Лужская",
      returnStation: "Шубарколь",
      calculatedTurnover: 31,
      approach: 0,
      loading: 4,
      loadedRun: 12,
      unloading: 3,
      return: 12,
      carDays: 31,
      clientRate: "757 456,00",
      emptyTariff: "250 230,00",
      loadedTariff: "416 482,00",
      provisionIncome: "90 744,00",
      dailyProfitability: "2 835,75",
      totalAmount: "757 456,00",
      deadEndPerDay: "1 200,00",
      supply: "да",
      day1: 4,
      day2: 3,
      day3: 12,
      wagonNumber: "44444",
      note: "",
    },
  ];

  switch (columnId) {
    case "optimizerPlan":
      return baseData.map((row) => ({
        ...row,
        status: row.status.includes("не обеспечен")
          ? "не обеспечен, по ограничениям"
          : "обеспечен",
      }));
    case "projectPlan":
      return baseData.map((row) => ({
        ...row,
        status: row.status.includes("обеспечен") ? "выгрузка +3" : row.status,
        note: row.status.includes("обеспечен") ? "принят" : row.note,
      }));
    case "approvedPlan":
      return baseData.map((row) => ({
        ...row,
        status: row.status.includes("обеспечен")
          ? ["ПОЗЖЕ", "РАВНО", "РАНЬШЕ"][Math.floor(Math.random() * 3)]
          : row.status,
      }));
    case "execution":
      return baseData.map((row) => ({
        ...row,
        status: row.status.includes("обеспечен")
          ? ["ПОЗЖЕ", "РАВНО"][Math.floor(Math.random() * 2)]
          : row.status,
      }));
    default:
      return baseData;
  }
}
