import type { LogisticsData } from "@/types";

export const mockData: LogisticsData = {
  demand: {
    rows: [
      {
        id: "№82 от 18.09.2024",
        status: "обеспечен 3 из 10",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №123",
        status: "обеспечен",
        note: "",
        wagonNumber: "111111",
      },
      {
        id: "Заявка №124",
        status: "обеспечен с корректировкой",
        note: "",
        wagonNumber: "222222",
      },
      {
        id: "Заявка №125",
        status: "обеспечен, с корректировкой по ограничениям",
        note: "",
        wagonNumber: "333333",
      },
      {
        id: "Заявка №126",
        status: "не обеспечен, по ограничениям",
        note: "1234, 33",
        wagonNumber: "",
      },
      {
        id: "Заявка №127",
        status: "не обеспечен, по ограничениям",
        note: "1234, 33",
        wagonNumber: "",
      },
      {
        id: "Заявка №128",
        status: "не обеспечен, по ограничениям",
        note: "1234, 33",
        wagonNumber: "",
      },
      {
        id: "Заявка №129",
        status: "не обеспечен, по ограничениям",
        note: "1234, 33",
        wagonNumber: "",
      },
      {
        id: "Заявка №130",
        status: "обеспечен",
        note: "",
        wagonNumber: "44444",
      },
      {
        id: "Заявка №131",
        status: "не обеспечен, по ограничениям",
        note: "1234, 33",
        wagonNumber: "",
      },
      {
        id: "Заявка №132",
        status: "не обеспечен, по ограничениям",
        note: "1234, 33",
        wagonNumber: "",
      },
    ],
  },
  optimizerPlan: {
    rows: [
      {
        id: "№82 от 18.09.2024",
        status: "обеспечен",
        note: "",
        wagonNumber: "111111",
      },
      {
        id: "Заявка №123",
        status: "обеспечен",
        note: "",
        wagonNumber: "222222",
      },
      {
        id: "Заявка №124",
        status: "обеспечен",
        note: "",
        wagonNumber: "333333",
      },
      {
        id: "Заявка №125",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №126",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №127",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №128",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №129",
        status: "обеспечен",
        note: "",
        wagonNumber: "44444",
      },
      {
        id: "Заявка №130",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №131",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №132",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
    ],
  },
  projectPlan: {
    rows: [
      {
        id: "№82 от 18.09.2024",
        status: "выгрузка +3, плановая",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №123",
        status: "выгрузка +3",
        note: "принят",
        wagonNumber: "22222",
      },
      {
        id: "Заявка №124",
        status: "выгрузка +3",
        note: "принят",
        wagonNumber: "33333",
      },
      {
        id: "Заявка №125",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №126",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №127",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №128",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      { id: "Заявка №129", status: "обеспечен", note: "", wagonNumber: "" },
      {
        id: "Заявка №130",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №131",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №132",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
    ],
  },
  approvedPlan: {
    rows: [
      {
        id: "№82 от 18.09.2024",
        status: "ПОЗЖЕ",
        note: "",
        wagonNumber: "3423423",
      },
      { id: "Заявка №123", status: "РАВНО", note: "", wagonNumber: "3434345" },
      { id: "Заявка №124", status: "РАНЬШЕ", note: "", wagonNumber: "2342344" },
      {
        id: "Заявка №125",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №126",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №127",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №128",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      { id: "Заявка №129", status: "обеспечен", note: "", wagonNumber: "" },
      {
        id: "Заявка №130",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №131",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №132",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
    ],
  },
  execution: {
    rows: [
      {
        id: "№82 от 18.09.2024",
        status: "ПОЗЖЕ",
        note: "",
        wagonNumber: "3423423",
      },
      { id: "Заявка №123", status: "РАВНО", note: "", wagonNumber: "3434345" },
      { id: "Заявка №124", status: "РАВНО", note: "", wagonNumber: "2342344" },
      {
        id: "Заявка №125",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №126",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №127",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №128",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      { id: "Заявка №129", status: "обеспечен", note: "", wagonNumber: "" },
      {
        id: "Заявка №130",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №131",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
      {
        id: "Заявка №132",
        status: "не обеспечен, по ограничениям",
        note: "",
        wagonNumber: "",
      },
    ],
  },
};
